
package tcClient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TempConvertService", targetNamespace = "http://tc/", wsdlLocation = "file:/home/mkalin/jwsur2/ch6/tempConvert/TempConvertService.wsdl")
public class TempConvertService
    extends Service
{

    private final static URL TEMPCONVERTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(tcClient.TempConvertService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = tcClient.TempConvertService.class.getResource(".");
            url = new URL(baseUrl, "file:/home/mkalin/jwsur2/ch6/tempConvert/TempConvertService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/mkalin/jwsur2/ch6/tempConvert/TempConvertService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TEMPCONVERTSERVICE_WSDL_LOCATION = url;
    }

    public TempConvertService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TempConvertService() {
        super(TEMPCONVERTSERVICE_WSDL_LOCATION, new QName("http://tc/", "TempConvertService"));
    }

    /**
     * 
     * @return
     *     returns TempConvert
     */
    @WebEndpoint(name = "TempConvertPort")
    public TempConvert getTempConvertPort() {
        return super.getPort(new QName("http://tc/", "TempConvertPort"), TempConvert.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TempConvert
     */
    @WebEndpoint(name = "TempConvertPort")
    public TempConvert getTempConvertPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tc/", "TempConvertPort"), TempConvert.class, features);
    }

}
