
package clientEJB;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PredictionEJBService", targetNamespace = "http://predEJB/", wsdlLocation = "http://localhost:8081/PredictionEJBService/PredictionEJB?wsdl")
public class PredictionEJBService
    extends Service
{

    private final static URL PREDICTIONEJBSERVICE_WSDL_LOCATION;
    private final static WebServiceException PREDICTIONEJBSERVICE_EXCEPTION;
    private final static QName PREDICTIONEJBSERVICE_QNAME = new QName("http://predEJB/", "PredictionEJBService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/PredictionEJBService/PredictionEJB?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PREDICTIONEJBSERVICE_WSDL_LOCATION = url;
        PREDICTIONEJBSERVICE_EXCEPTION = e;
    }

    public PredictionEJBService() {
        super(__getWsdlLocation(), PREDICTIONEJBSERVICE_QNAME);
    }

    public PredictionEJBService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PREDICTIONEJBSERVICE_QNAME, features);
    }

    public PredictionEJBService(URL wsdlLocation) {
        super(wsdlLocation, PREDICTIONEJBSERVICE_QNAME);
    }

    public PredictionEJBService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PREDICTIONEJBSERVICE_QNAME, features);
    }

    public PredictionEJBService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PredictionEJBService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PredictionEJB
     */
    @WebEndpoint(name = "PredictionEJBPort")
    public PredictionEJB getPredictionEJBPort() {
        return super.getPort(new QName("http://predEJB/", "PredictionEJBPort"), PredictionEJB.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PredictionEJB
     */
    @WebEndpoint(name = "PredictionEJBPort")
    public PredictionEJB getPredictionEJBPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://predEJB/", "PredictionEJBPort"), PredictionEJB.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PREDICTIONEJBSERVICE_EXCEPTION!= null) {
            throw PREDICTIONEJBSERVICE_EXCEPTION;
        }
        return PREDICTIONEJBSERVICE_WSDL_LOCATION;
    }

}
