
package clientAxis2;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "hi", targetNamespace = "http://hello", wsdlLocation = "http://localhost:8080/axis2/services/hi?wsdl")
public class Hi
    extends Service
{

    private final static URL HI_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(clientAxis2.Hi.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = clientAxis2.Hi.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/axis2/services/hi?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/axis2/services/hi?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        HI_WSDL_LOCATION = url;
    }

    public Hi(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Hi() {
        super(HI_WSDL_LOCATION, new QName("http://hello", "hi"));
    }

    /**
     * 
     * @return
     *     returns HiPortType
     */
    @WebEndpoint(name = "hiHttpSoap11Endpoint")
    public HiPortType getHiHttpSoap11Endpoint() {
        return super.getPort(new QName("http://hello", "hiHttpSoap11Endpoint"), HiPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HiPortType
     */
    @WebEndpoint(name = "hiHttpSoap11Endpoint")
    public HiPortType getHiHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://hello", "hiHttpSoap11Endpoint"), HiPortType.class, features);
    }

    /**
     * 
     * @return
     *     returns HiPortType
     */
    @WebEndpoint(name = "hiHttpSoap12Endpoint")
    public HiPortType getHiHttpSoap12Endpoint() {
        return super.getPort(new QName("http://hello", "hiHttpSoap12Endpoint"), HiPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HiPortType
     */
    @WebEndpoint(name = "hiHttpSoap12Endpoint")
    public HiPortType getHiHttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://hello", "hiHttpSoap12Endpoint"), HiPortType.class, features);
    }

    /**
     * 
     * @return
     *     returns HiPortType
     */
    @WebEndpoint(name = "hiHttpEndpoint")
    public HiPortType getHiHttpEndpoint() {
        return super.getPort(new QName("http://hello", "hiHttpEndpoint"), HiPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HiPortType
     */
    @WebEndpoint(name = "hiHttpEndpoint")
    public HiPortType getHiHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://hello", "hiHttpEndpoint"), HiPortType.class, features);
    }

}
