
package clientAsync;

import java.util.List;
import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "RandService", targetNamespace = "http://rand/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RandService {


    /**
     * 
     * @return
     *     returns javax.xml.ws.Response<clientAsync.Next1Response>
     */
    @WebMethod(operationName = "next1")
    @RequestWrapper(localName = "next1", targetNamespace = "http://rand/", className = "clientAsync.Next1")
    @ResponseWrapper(localName = "next1Response", targetNamespace = "http://rand/", className = "clientAsync.Next1Response")
    public Response<Next1Response> next1Async();

    /**
     * 
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "next1")
    @RequestWrapper(localName = "next1", targetNamespace = "http://rand/", className = "clientAsync.Next1")
    @ResponseWrapper(localName = "next1Response", targetNamespace = "http://rand/", className = "clientAsync.Next1Response")
    public Future<?> next1Async(
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<Next1Response> asyncHandler);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "next1", targetNamespace = "http://rand/", className = "clientAsync.Next1")
    @ResponseWrapper(localName = "next1Response", targetNamespace = "http://rand/", className = "clientAsync.Next1Response")
    public int next1();

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<clientAsync.NextNResponse>
     */
    @WebMethod(operationName = "nextN")
    @RequestWrapper(localName = "nextN", targetNamespace = "http://rand/", className = "clientAsync.NextN")
    @ResponseWrapper(localName = "nextNResponse", targetNamespace = "http://rand/", className = "clientAsync.NextNResponse")
    public Response<NextNResponse> nextNAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "nextN")
    @RequestWrapper(localName = "nextN", targetNamespace = "http://rand/", className = "clientAsync.NextN")
    @ResponseWrapper(localName = "nextNResponse", targetNamespace = "http://rand/", className = "clientAsync.NextNResponse")
    public Future<?> nextNAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<NextNResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Integer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "nextN", targetNamespace = "http://rand/", className = "clientAsync.NextN")
    @ResponseWrapper(localName = "nextNResponse", targetNamespace = "http://rand/", className = "clientAsync.NextNResponse")
    public List<Integer> nextN(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
