
package clientAsync;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "RandServiceService", targetNamespace = "http://rand/", wsdlLocation = "http://localhost:8888/rs?wsdl")
public class RandServiceService
    extends Service
{

    private final static URL RANDSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(clientAsync.RandServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = clientAsync.RandServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8888/rs?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8888/rs?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        RANDSERVICESERVICE_WSDL_LOCATION = url;
    }

    public RandServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RandServiceService() {
        super(RANDSERVICESERVICE_WSDL_LOCATION, new QName("http://rand/", "RandServiceService"));
    }

    /**
     * 
     * @return
     *     returns RandService
     */
    @WebEndpoint(name = "RandServicePort")
    public RandService getRandServicePort() {
        return super.getPort(new QName("http://rand/", "RandServicePort"), RandService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RandService
     */
    @WebEndpoint(name = "RandServicePort")
    public RandService getRandServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://rand/", "RandServicePort"), RandService.class, features);
    }

}
